[unix_http_server]
file=/tmp/supervisor.sock

[supervisord]
logfile=run/supervisord.log
logfile_maxbytes=20MB
logfile_backups=3
loglevel=info
pidfile=run/supervisord.pid
nodaemon=false
minfds=1024
minprocs=200

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:findex_main]
directory=/Users/tmkd/Desktop/tmkd/FindexHub
command=/Users/tmkd/Desktop/tmkd/FindexHub/venv/bin/python /Users/tmkd/Desktop/tmkd/FindexHub/main.py
autostart=true
autorestart=true
startsecs=3
stdout_logfile=run/main_bot.log
stderr_logfile=run/main_bot_err.log
environment=BOT_TOKEN="%(ENV_BOT_TOKEN)s",MAIN_CHANNEL_ID="-1003148024541",PYTHONUNBUFFERED="1"

[program:support_bot]
directory=/Users/tmkd/Desktop/tmkd/FindexHub/support_bot
command=/Users/tmkd/Desktop/tmkd/FindexHub/support_bot/venv/bin/python /Users/tmkd/Desktop/tmkd/FindexHub/support_bot/support_bot.py
autostart=true
autorestart=true
startsecs=3
stdout_logfile=run/support_bot.log
stderr_logfile=run/support_bot_err.log
environment=BOT_TOKEN="%(ENV_SUPPORT_BOT_TOKEN)s",SUPPORT_GROUP_ID="-1003156953720",SUPPORT_ADMIN_ID="6823902949",PYTHONUNBUFFERED="1"

