"""init db

Revision ID: 3e7c3e916c80
Revises: 
Create Date: 2026-01-26 20:12:36.481704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e7c3e916c80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('watch_role', sa.String(length=32), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_role_active', 'alerts', ['watch_role', 'is_active'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.BigInteger(), nullable=False),
    sa.Column('user_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ad_id', 'user_tg_id', name='uq_delivery_ad_user')
    )
    op.create_index('ix_deliveries_ad', 'deliveries', ['ad_id'], unique=False)
    op.create_index(op.f('ix_deliveries_ad_id'), 'deliveries', ['ad_id'], unique=False)
    op.create_index(op.f('ix_deliveries_user_tg_id'), 'deliveries', ['user_tg_id'], unique=False)
    op.drop_index(op.f('idx_moderation_actions_ad_id'), table_name='moderation_actions')
    op.drop_table('moderation_actions')
    op.drop_index(op.f('idx_payments_ad_id'), table_name='payments')
    op.drop_index(op.f('idx_payments_status'), table_name='payments')
    op.drop_index(op.f('idx_payments_user_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('idx_daily_limits_day_key'), table_name='daily_limits')
    op.drop_table('daily_limits')
    op.alter_column('ads', 'status',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ads', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('ads_ad_no_key'), 'ads', type_='unique')
    op.drop_index(op.f('idx_ads_author_user_id'), table_name='ads')
    op.drop_index(op.f('idx_ads_moderation_msg'), table_name='ads')
    op.drop_index(op.f('idx_ads_payment_status'), table_name='ads')
    op.drop_index(op.f('idx_ads_scheduled_at'), table_name='ads')
    op.drop_index(op.f('idx_ads_status'), table_name='ads')
    op.drop_index(op.f('idx_ads_user_msg'), table_name='ads')
    op.create_index(op.f('ix_ads_author_user_id'), 'ads', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_ads_status'), 'ads', ['status'], unique=False)
    op.create_index('ix_ads_status_created', 'ads', ['status', 'created_at'], unique=False)
    op.drop_constraint(op.f('ads_author_user_id_fkey'), 'ads', type_='foreignkey')
    op.drop_column('ads', 'moderation_message_id')
    op.drop_column('ads', 'ad_no')
    op.drop_column('ads', 'payment_method')
    op.drop_column('ads', 'user_chat_id')
    op.drop_column('ads', 'price_rub')
    op.drop_column('ads', 'moderation_chat_id')
    op.drop_column('ads', 'scheduled_at')
    op.drop_column('ads', 'payment_amount')
    op.drop_column('ads', 'publish_mode')
    op.drop_column('ads', 'user_message_id')
    op.drop_column('ads', 'payment_id')
    op.drop_column('ads', 'payment_meta')
    op.drop_column('ads', 'user_has_caption')
    op.drop_column('ads', 'payment_status')
    op.drop_column('ads', 'main_message_id')
    op.drop_column('ads', 'main_channel_id')
    op.add_column('users', sa.Column('username', sa.String(length=128), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_index(op.f('idx_users_tg_user_id'), table_name='users')
    op.drop_constraint(op.f('users_tg_user_id_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_user_no_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_tg_user_id'), 'users', ['tg_user_id'], unique=True)
    op.drop_column('users', 'user_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_no', sa.BIGINT(), server_default=sa.text("nextval('user_no_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_users_tg_user_id'), table_name='users')
    op.create_unique_constraint(op.f('users_user_no_key'), 'users', ['user_no'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_tg_user_id_key'), 'users', ['tg_user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_tg_user_id'), 'users', ['tg_user_id'], unique=False)
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('users', 'username')
    op.add_column('ads', sa.Column('main_channel_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('main_message_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('payment_status', sa.TEXT(), server_default=sa.text("'none'::text"), autoincrement=False, nullable=False))
    op.add_column('ads', sa.Column('user_has_caption', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('ads', sa.Column('payment_meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('ads', sa.Column('payment_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('user_message_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('publish_mode', sa.TEXT(), server_default=sa.text("'free'::text"), autoincrement=False, nullable=False))
    op.add_column('ads', sa.Column('payment_amount', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('moderation_chat_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('price_rub', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('ads', sa.Column('user_chat_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('payment_method', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ads', sa.Column('ad_no', sa.BIGINT(), server_default=sa.text("nextval('ad_no_seq'::regclass)"), autoincrement=True, nullable=False))
    op.add_column('ads', sa.Column('moderation_message_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('ads_author_user_id_fkey'), 'ads', 'users', ['author_user_id'], ['id'], ondelete='RESTRICT')
    op.drop_index('ix_ads_status_created', table_name='ads')
    op.drop_index(op.f('ix_ads_status'), table_name='ads')
    op.drop_index(op.f('ix_ads_author_user_id'), table_name='ads')
    op.create_index(op.f('idx_ads_user_msg'), 'ads', ['user_chat_id', 'user_message_id'], unique=False)
    op.create_index(op.f('idx_ads_status'), 'ads', ['status'], unique=False)
    op.create_index(op.f('idx_ads_scheduled_at'), 'ads', ['scheduled_at'], unique=False)
    op.create_index(op.f('idx_ads_payment_status'), 'ads', ['payment_status'], unique=False)
    op.create_index(op.f('idx_ads_moderation_msg'), 'ads', ['moderation_chat_id', 'moderation_message_id'], unique=False)
    op.create_index(op.f('idx_ads_author_user_id'), 'ads', ['author_user_id'], unique=False)
    op.create_unique_constraint(op.f('ads_ad_no_key'), 'ads', ['ad_no'], postgresql_nulls_not_distinct=False)
    op.alter_column('ads', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('ads', 'status',
               existing_type=sa.TEXT(),
               server_default=sa.text("'draft'::text"),
               existing_nullable=False)
    op.create_table('daily_limits',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('day_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('count_used', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('daily_limits_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('daily_limits_pkey')),
    sa.UniqueConstraint('user_id', 'day_key', name=op.f('daily_limits_user_id_day_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_daily_limits_day_key'), 'daily_limits', ['day_key'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('ad_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('method', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('amount_rub', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount_crypto', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('provider', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('external_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tx_hash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], name=op.f('payments_ad_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('payments_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_pkey')),
    sa.UniqueConstraint('payment_id', name=op.f('payments_payment_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_index(op.f('idx_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('idx_payments_ad_id'), 'payments', ['ad_id'], unique=False)
    op.create_table('moderation_actions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('ad_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('moderator_tg_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], name=op.f('moderation_actions_ad_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('moderation_actions_pkey'))
    )
    op.create_index(op.f('idx_moderation_actions_ad_id'), 'moderation_actions', ['ad_id'], unique=False)
    op.drop_index(op.f('ix_deliveries_user_tg_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_ad_id'), table_name='deliveries')
    op.drop_index('ix_deliveries_ad', table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index('ix_alerts_role_active', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
