"""deliveries retry fields

Revision ID: 7a63953390aa
Revises: 9e2b62c4b8d9
Create Date: <AUTOGENERATED>

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a63953390aa"
down_revision: Union[str, Sequence[str], None] = "9e2b62c4b8d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1) attempts: сколько попыток отправки
    op.add_column(
        "deliveries",
        sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
    )

    # 2) next_retry_at: когда пробуем снова (NULL = можно пробовать сразу)
    op.add_column(
        "deliveries",
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
    )

    # 3) updated_at: для контроля жизненного цикла (и удобной отладки)
    op.add_column(
        "deliveries",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )

    # 4) дефолт статуса (опционально, но удобно): pending вместо “что попадёт”
    # Важно: status у тебя NOT NULL, но дефолт в \d не видно — значит он может отсутствовать.
    # Мы безопасно поставим DEFAULT 'pending'.
    op.execute("ALTER TABLE deliveries ALTER COLUMN status SET DEFAULT 'pending';")

    # 5) индекс для выборки задач на ретрай:
    # status + next_retry_at (быстро брать pending/failed, у которых пора ретраить)
    op.create_index(
        "ix_deliveries_retry",
        "deliveries",
        ["status", "next_retry_at"],
        unique=False,
    )

    # 6) убрать server_default у attempts, чтобы “чисто” (не обязательно, но аккуратно)
    op.alter_column("deliveries", "attempts", server_default=None)


def downgrade() -> None:
    # откат индекса
    op.drop_index("ix_deliveries_retry", table_name="deliveries")

    # откат дефолта статуса
    op.execute("ALTER TABLE deliveries ALTER COLUMN status DROP DEFAULT;")

    # откат колонок
    op.drop_column("deliveries", "updated_at")
    op.drop_column("deliveries", "next_retry_at")
    op.drop_column("deliveries", "attempts")
